### ISSUE TITLE
Documentation edits needed

### ISSUE THREAD

**Issue by dsquaredb** [elmsln/haxcms#11]
My initial attempt to use DDEV to get haxcms going wasn't quite right. While I could create a new site, I couldn't access them. I attribute this to user error and maybe a bit of needed docs. Here are my suggestions for the "Play immediately with DDEV" section:

1. Clone the haxcms github repo locally using the Clone with HTTPS option. (I initially tried clone with SSH and didn't have the proper credentials, so then tried Download ZIP which had some issues. )

2. Add that you will be logged into HAXCMS when you start it up this way. (I initially tried to login by clicking the icon in the upper right corner and it logged me out.)

When I tried again with the right clone, it worked great and I could access my sites.

**Comment by btopro** [comment]
Thank you for the feedback! I updated docs a bit w/ more direct commands / links to docker (since I know not everyone will have that too).

As for logging in / ux of haxcms itself that's a different exercise as I'm very aware it has no work put into 'wtf is this' :). This is mostly proof of concept bc if this stuff works then we can bother to work on the UX and then start having people build out from there.

Thanks again!
