### ISSUE TITLE
Character bugs

### ISSUE THREAD

**Issue by tomsshow** [elmsln/haxcms#28]
I am using the simple blogging theme and any time "s" and "t" are typed next to each other the two letters combine or join together. Also bolding a single letter will auto create a space after it. I was trying to define HAX in my blog post. **H**eadless **A**uthoring e**X**perience is what I wanted, but it will save as   **H** eadless **A** uthoring e**X** perience.

**Comment by btopro** [comment]
move `Also bolding a single letter will auto create a space after it. I was trying to define HAX in my blog post. Headless Authoring eXperience is what I wanted, but it will save as H eadless A uthoring eX perience.` over to https://github.com/LRNWebComponents/hax-body/issues since that's a core issue w/ HAX itself (and I know what would cause that and its totally legit).

As for the s and t thing that's something in the CSS of that theme; I noticed it too but I think it's actually in the font to render silly like that

**Comment by btopro** [comment]
open a new issue over there and close this one once you've done so, thanks for the report!
