### ISSUE TITLE
small bug: extra space added in link text before final punctuation

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#305]
I've noticed an odd thing when I am creating links; if there is punctuation following (like a period or colon), HAX is adding an extra space at the end of the link text and before the punctuation. This happens even when I go in and try to remove the space. Here's a screenshot; it's not a problem when there is no following punctuation, but when I am trying to put a colon directly after the link text, there is that extra space:
https://hax.lauragibbs.net/sites/story-folder/item-a46c25d6-b44b-46ac-b2e6-4d60c45ba117
Yes, I am enough of an editing nerd to want to get rid of that space, ha ha. Nothing urgent, but it would be nice to fix if possible. 

![Screen Shot 2019-07-01 at 1 23 14 PM](https://user-images.githubusercontent.com/19476543/60455146-b1015400-9c03-11e9-94d7-cbc21e53075f.png)

**Comment by btopro** [comment]
well there went the whole morning "fixing this small issue" (in my mind).

Turns out it was related to how we sanitize pasting and building the body of content. By fixing copy/paste the same clean up was applied to situations where this would happen. Running a build now to do more testing but this should now be fixed (and a lot of other copy/paste/word compat issues).
