### ISSUE TITLE
bug? feature request? copying-and-pasting loses formatting

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#306]
I've been doing my editing outside of HAX and pasting into the HTML view; I haven't been using the WYSIWYG much. But today I messed something up and had to copy and paste, and I realized that all the formatting disappeared, even when copying-and-pasting inside the HAX editing space. I had a chunk of text which contained a hyperlink and which also contained a line break, and when I copied-and-pasted, the text lost the link and it lost the line break.
This is not a big deal for this project since I'm not really using HAX as a composing/editing space, but my guess is that people expect to be able to retain formatting when they copy and paste.
So, I'm not sure if this is a bug (?) or a feature request (?), but it's something to consider going forward. Is there some kind of copying-and-pasting button or something inside HAX that we're supposed to use maybe...?

**Comment by btopro** [comment]
Tagging this as security related. @nikkimk might have a new UX pattern for PASTE vs PASTE AND SCRUB. Currently we scrub everything because of previous data sanitization things we were doing. What we might want to do instead is that when paste is executed in HAX, analyze the contents being pasted in and run them through our "take out style and script tags" function. This will give us the sanitization needed while preserving formatting as is to be expected.

**Comment by lauragibbs** [comment]
Oh, that would be super! I'm available to test that out anytime. I'm doing just fine editing outside HAX, but it would save me a step or two if I could copy-and-paste without losing all the formatting. :-)

**Comment by btopro** [comment]
I believe I have a fix for this that both strips word content and provides a secure method of allowing formatting through, as well as copying hax pages between each other while preserving the components underneath.

Will be in the next release and I'll close once that's tested and up (hopefully tomorrow)

**Comment by btopro** [comment]
fixed
