### ISSUE TITLE
Is it possible to integrate HAXeditor in Joomla?

### ISSUE THREAD

**Issue by richardsullivan** [elmsln/HAXcms#318]
Sorry if this is the wrong place for such a general question.

I'm an IT freelancer and am currently helping a client pick a CMS. 
My contact at the client's organisation has a preference for Joomla (based upon her familiarity with Joomla elsewhere in the past).

As far as I know, there isn't any HAX integration available for Joomla at the moment.
Are there any plans to provide an integration for Joomla ? 
Are there any technical reasons which would prevent someone (worst case me) from developing an integration? 

Thanks,
Richard

**Comment by btopro** [comment]
This queue is fine. Good question. We'd love for there to be a HAX plugin for Joomla and provide generic PHP classes that speed up integration, so no there's no reason there couldn't be a Joomla plugin. I've just never made one and didn't have a reason to but I'd gladly provide advisement in getting one created if you took the lead on it. We want HAX for every platform imaginable. If you look at the Drupal 7, WordPress and gravcms integrations you'll see they arn't terribly different in how they integrate and they use a class that helps write the "appstore" specification mentioned on the haxtheweb.org site

**Comment by btopro** [comment]
some reference links:
- some classes to help w/ integrations - https://github.com/elmsln/hax_php_lib

A few integrations that then implement these / other classes

- D8 - https://git.drupalcode.org/project/hax
- WordPress - https://github.com/elmsln/wp-plugin-hax
- GravCMS - https://github.com/elmsln/grav-plugin-hax

Some ecosystems also have a webcomponents plugin/module which leverages some classes from the 1st repo. While not required, they help implement the methodology of integration that I tend towards for progressive enhancement integrations. My guess is joomla won't need this as it already has some web components in core (Im not part of that community but have talked off and on in the past so that might not be the case but it's what I discerned from those discussions)

**Comment by btopro** [comment]
question hopefully answered. @richardsullivan I'd be happy to help answer any questions relative to this integration on twitter or in another thread sometime. Closing out for tidying things up but yes, it is possible and we'd love to help.
