### ISSUE TITLE
Editing Grav pages with HAX Editor - HTML translation issue

### ISSUE THREAD

**Issue by paulhibbitts** [elmsln/HAXcms#452]
For certain types of Grav pages, there are issues if these pages are fully translated to HTML as Grav page processing is based on the expectation of Markdown being used. This may result in Grav sites to appear "broken" if the HAX Editor is used to save pages.

For example, blog post page types use a separator in Markdown to determine page summary and content body (i.e. "==="), so when translated to HTML blog post summary and content separate seems to be lost. You can see this if you edit a blog post page with HAX, and then view the blog list parent page - the displayed summary will use summary length vs. an existing separator for summary display. 

Another example is the Presentation Plugin, where if the Presentation page (containing multiple slides using a separator (i.e."---") is edited then it seems that all slides but one are lost, but really the content is still there but has been translated to HTML and it is no longer to use separators to determine slide break points.

There are likely more scenarios where this translation is an issue, but the above two are ones I've seen so far. 

Since many people choose Grav because it is a Markdown CMS (which is not true with WordPress, Drupal, etc.), it could be preferable to use HAX as a WYSIWYG block editor for Markdown content, and then perhaps have the option to use HTML elements within Markdown - might this at all be possible? Perhaps another option is to recognize common Markdown content separators, and use HTML content areas above and below these (and keep the separators)? I can provide example files for reference.

I am still trying to get a sense of the best positioning of HAX for Grav folks🙂 As I've said, I also see that there is an audience segment that could be further drawn to Grav _without_ the use of Markdown.

Thanks for all your work in this area! I look forward to hearing your thoughts.
Paul

**Comment by btopro** [comment]
Thank you for the report and detail. I wonder, does this affect "head matter" as well or is it just in the method of formatting in the document? We recently did a thing in elmsln on an internal deploy where we had all of these "tokens" that looked like this `[oldsystem|render|node|123|image]` sorta thing. We were concerned about migrating them to new tokens because while we were here, let's just move it to "hax" capable content (aka html).

We also were concerned though about not having "hax" capable translations for everything. There were lots of divs and legacy image gallery types that we didn't want to upgrade (because they aren't up to modern standards we NOW use but this is content at times 8+ years old migrated across 3 different solutions). So, the solution we arrived at looked like this:

- Take the content from the token call (let's say it's `<div>blahblah</div>`)
- Wrap it in a `<html-block>` tag
- insert it in the document where it was before

This allowed elmsln to upgrade older contents but then when someone goes to use HAX, they'll still get a selection of it as a single item and the ability to modify it as HTML directly (as it wasn't a block before we don't really know what it is so this is better then gobbling it).

So, I lay this out because, what if we did something similar with existing content, leaving a flag in the head matter to indicate that HAX has modified the page or not? This would then allow us at run time if editing something that HAS content (so assumed markdown, created prior) to wrap the contents in a `<md-block>` tag (which we already have) to preserve the MD formatting.

Then other things could be modified using HAX in the page as expected but that area acts as a "block" of its own. Thoughts on something like this as a possible bridge between the worlds? I agree there's a bit of "Grav is for MD" to how you frame things, and my students in class liked it, but then they immediately gravitated to Gutenberg / block editors and all of them then recommended WP over Grav.

Anecdotal evidence, but I think the audience for Grav that cares about MD is probably semi to highly technical. I did have 1 student start building his own sites in Grav, and he's the most technical in the class so it seemed to match the guess as well.

Another possibility is to add a flag much like the "process with twig" or "process as markdown" settings, to have a "use HAX to edit" option or something like that when creating a new page. This would then set a flag in the headmatter to even use HAX, and the old editor would show up for existing content. Then if power users wanted to convert a MD page to a HAX page we could give them a setting in advanced and they could be notified of the things you laid out above.

**Comment by paulhibbitts** [comment]
Hey @btopro , thanks for the detailed response!

In terms of page frontmatter that seems to be left alone in the current implementation as far as I can tell.

Grav is indeed intended for a more technically-oriented audience by design, in particular for a level of customization which in other platforms would be a lot more resource-intensive, also for those prefer Markdown-based workflows.

In terms of options to handle the original issue reported, it depends on how you see the HAX Plugin being used in Grav. For example, as a means to have Grav users "test drive" HAX a bit and then perhaps use a more suitable HAX platform, to fully switch over from Markdown to HTML, etc. To be adaptive to these possible use cases, on first-pass I like this idea of yours:

_So, I lay this out because, what if we did something similar with existing content, leaving a flag in the head matter to indicate that HAX has modified the page or not? This would then allow us at run time if editing something that HAS content (so assumed markdown, created prior) to wrap the contents in a <md-block> tag (which we already have) to preserve the MD formatting._

If I understand correctly, then this might address the blog summary/content separator issue if there are no unexpected consequences with the page content modifications (there still might be though as content would be "split" within the MD block tag into page summary/content). For the scenario of Markdown Presentation files though, I think adding any block boundaries etc could still break things.

Might it be possible to have some sort of config to add template names in the HAX Config which are only to be edited using the standard Markdown editor? What do you think of that idea? As a real scenario, I could see making blog posts and presentation type pages MD editor only, but using HAX for new standard pages and perhaps new modular pages.

These are just some initial thoughts etc. Looking forward to your thoughts about the above!

**Comment by btopro** [comment]
I don't understand the grav way of doing template types but that sounds reasonable. As far as HAX positioning in Grav, the goal is to enhance the authoring experience of all platforms with a goal of long term making it easier for normal people to migrate previously complex content between systems. Anyone can copy and paste, no one can do that with WordPress and Drupal now and Grab markdown then requires other solutions have an identical markdown interpretation. I see HAX as a way to make Grav more palatable to less technical users. This is again, assuming we keep enhancing the integration as well as ux of hax itself. We are not here to conquer, we come seeking a stronger relationship between islands (CMSs)

**Comment by paulhibbitts** [comment]
Let's see how things go with hopefully more Reclaim folks giving it a go and providing you with feedback etc. The templates that seem to not work with the HTML Translation so far are `item`, `presentation` and `slide`. Alternatively, you could also try your idea of using some sort of a MD block and see if things work out etc.

**Comment by paulhibbitts** [comment]
BTW, now that I've spent a bit more time exploring web components I'd tend to see them integrated into Grav via a theme, where one can continue to use Grav as a Markdown-based CMS and at the same time fully leverage web components via Markdown (i.e. Shortcodes) and pure HTML. How feasible is that?

**Comment by btopro** [comment]
Totally feasible. We use webcomponents in elmsln theme layer for 3 years. Hax coming out of a natural progression

**Comment by paulhibbitts** [comment]
Cool. There have been rumblings about web components possibly being part of Bootstrap 6 as well, which I use (v4) as my base for the Open Course Hub theme. I don't have an immediate need for WC, but as a longer-term vision of integration with Grav this will be one avenue I would keep my eye on for sure👍. I know you prefer a Plugin approach (vs. Theme), might your current Grav Web Components Plugin possibly provide an interface to WC via existing Grav Markdown/HTML pages, and if not how much work to do so? Just trying to better understand possibilities 🙂

**Comment by btopro** [comment]
Webcomponents plugin can be used by itself. Image it getting the theme layers dependencies tree out if the way so you could use video player in a homepage template AND in random pages within. Or UI buttons, too bar menu to interface, anything that webcomponents supplied provide

**Comment by paulhibbitts** [comment]
Thanks for all the helpful info Bryan! At some point, time permitting, it would be great to see one working example of this and depending on the technical complexities etc I could start to explore if that is something I can support in the future etc. I am a complete newbie to WC as you know, and not a dev🙂

**Comment by btopro** [comment]
Np. Oh you are far more a dev then you let on! Hit up open-wc.org it should help reveal a lot of how easy it's getting to get into webcomponents in all layers. Www.webcomponents.org  then to find pieces you can steal to build UIs faster and with higher accessibility without thinking about it 😁

**Comment by paulhibbitts** [comment]
🙂Hope to give this a go soon! Thanks again for the info.

**Comment by paulhibbitts** [comment]
For those following this thread, the first proof-of-concept! https://twitter.com/hibbittsdesign/status/1186036392461123584

**Comment by btopro** [comment]
woah wait how did you do that? did you make a new kind of short code or is that how they work in grav?

**Comment by paulhibbitts** [comment]
Indeed🙂 Thanks to your Web Components Plugin I made a sample shortcode to embed a WC https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/shortcodes/WCStopNoteShortcode.php

I'd like to next try to make a custom content type, as another possible approach.

**Comment by btopro** [comment]
#441 related

**Comment by paulhibbitts** [comment]
BTW, the more I got into creating that example the more I see getting access to Webcomponents via Shortcodes as a way to support those who want to work with a Markdown/Git workflow in Grav while still taking advantage of Webcomponents where valuable🙂

**Comment by btopro** [comment]
Grav integration improved a lot in the new release of GravCMS plugin + the UX updates to HAX in general. May still be conflicts w/ markdown but we've got a `md-block` tag which is also able to process this. Closing for now and can be opened based on new information as bugs pop up in Grav+HAX

**Comment by paulhibbitts** [comment]
Thanks for the update @btopro , I plan to check this out soon!
