### ISSUE TITLE
document github publishing workflow

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#70]
- run `haxtheweb.sh` or one of the containers/VMs that runs this on setup
- go to your sites dashboard
- login and hit settings button
- fill out the github / publishing information
- hit save

Now to publish a new site
- Hit 'add site' (example named `coolwebsite`)
- Go to `https://github.com/{yourname}` and create a new repo called `coolwebsite`
- go to the site and click the menu button, then hit settings
- hit the publishing button
- your new website should be available shortly

To republish / update changes to the site
- hit the publishing button :)

**Comment by btopro** [comment]
![haxcms workflow](https://user-images.githubusercontent.com/329735/52301968-c9718900-2959-11e9-9300-420b82b2316d.jpg)

**Comment by rickmanelius** [comment]
Ok! Here's testing for today. I was successful in setup, generating site 1, generating article 1 (partial), and pushing to GitHub. I got blocked on GitHub pages (manually) because I didn't realize this was the path for GitHub pages support. Here's a gist containing my step by step process as well as feedback along the way. https://gist.github.com/rickmanelius/31f37327b2f36b9cc00a960bcb403586

This is the repo containing the snapshot of my progress https://github.com/rickmanelius/test-deploy.

**Comment by btopro** [comment]
docs updated to reflect the things here and from the 2FA follow up thread
